spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

server:
  connection-timeout: 60000
  session.timeout: 60000
  port: 8080
  servlet:
    context-path: /api

management:
  security:
    enabled: false
  context-path: /api

endpoints:
  enabled: false
  health:
    enabled: true

services-security:
  username: one-dev
  password: 008a8005-c66a-4888-b115-32d95572c213
  role: API

  spring:
    data:
      mongodb:
      uri: mongodb://user:password@localhost:27017/mongodb
